layout_spectrum: 0.8995703
typography_spectrum: 0.02416755
color:
  saturation: 0.3259935
  lightness: 0.1895811
  brandStrength: 0.9124597
  rhythmicContrast: 0.6868958
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: GiantGingerDad
