name: GiantGingerDad
favicon: null
layout_spectrum: 0.8995703
typography_spectrum: 0.60004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5961bf'
    - '#5928b4'
    - '#4eb7c8'
    - '#c1bee5'
  brandStrength: 0.9124597
  lightness: 0.06605798
  saturation: 0.2626208
  rhythmicContrast: 0.7943072
purpose: []
